site_name: Token Audit Handbook
site_description: A handbook for practitioners to audit tokens (crypto-assets)
site_author: Shayan Eskandari
site_url: https://madibagroup.github.io/tokenhandbook/

# Repository
repo_name: MadibaGroup/tokenhandbook/
repo_url: https://github.com/MadibaGroup/tokenhandbook/
# edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Madiba Group'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: https://madiba.encs.concordia.ca


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Index: index.md
  # - Sections:
  #   - Index: sections/index.md
  - Background: 00-background/index.md
  - Valuation: 
      - Index: 01-valuation/01-index.md 
      - Fair Value: 01-valuation/02-Fair Value.md 
      - Liquidity: 01-valuation/03-Liquidity.md 
      - Financial Modelling: 01-valuation/04-Financial Modelling.md 
      - Bans: 01-valuation/05-Bans.md 
      - Cut-off: 01-valuation/06-Cut-off.md 
      - Geographical Variation: 01-valuation/07-Geographical Variation.md 
      - Fungibility: 01-valuation/08-Fungibility.md 
      - Financial Projections: 01-valuation/09-Financial Projections.md 
      - Volatility: 01-valuation/10-Volatility.md 
      - Going Concern: 01-valuation/11-Going Concern.md 
  - Existence: 
      - Index: 02-existence/01-index.md 
      - Meta Information: 02-existence/02-Meta Information.md 
      - Off-blockchian Transactions: 02-existence/03-Off-blockchian Transactions.md 
      - Finality: 02-existence/04-Finality.md 
      - Completeness: 02-existence/05-Completeness.md 
      - Transaction Complexity: 02-existence/06-Transaction Complexity.md 
      - Transaction Pointers: 02-existence/07-Transaction Pointers.md 
  - Ownership: 
      - Index: 03-ownership/01-index.md 
      - Custodianship: 03-ownership/02-Custodianship.md 
      - Account Balances: 03-ownership/03-Account Balances.md 
      - Cryptographic Key ownership: 03-ownership/04-Cryptographic Key ownership.md 
      - Balance itself: 03-ownership/05-Balance itself.md 
      - Design Transparency: 03-ownership/06-Design Transparency.md 
      - Related Party Transaction: 03-ownership/07-Related Party Transaction.md 
  - Presentation: 
      - Index: 04-presentation/01-index.md 
      - Reporting Standard: 04-presentation/02-Reporting Standard.md 
      - Legal status: 04-presentation/03-Legal status.md 

  - Uncategorized: 05-uncategorized/index.md
  #- Module Skeleton: module-blank.md

  # - Specimen: specimen.md
  # - Customization: customization.md
  # - Compliance with GDPR: compliance.md
  # - Release notes: release-notes.md
  # - Author's notes: authors-notes.md
  # - Contributing: contributing.md
  # - License: license.md

# Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto